# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f47be4b453e31588740062f03cbdab7a6e389d2eebde8d21ab9d0ba303a58c3770ff0251ced5f6c2f06352c1b4523af945bc41cd9bfd3d0dd8934adc6011527

test:
  secret_key_base: 0c880cfacdda3e6ea9dbcb09e54e229ccfa94f70b911808fbfc532648b8748a16f27ab3859bc91355b8f95ba3ca7ae39f91146905a8b307ca54485e9d83a73c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
